name: keyboard_layout_example
description: Demonstrates how to use the keyboard_layout plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  keyboard_layout:
    path: ../

flutter:
  uses-material-design: true
