name: keyboard_info
description: Provides API for querying information about the system keyboard.
homepage: https://github.com/jpnurmi/keyboard_info
repository: https://github.com/jpnurmi/keyboard_info
issue_tracker: https://github.com/jpnurmi/keyboard_info/issues
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  file: ^6.0.0
  flutter:
    sdk: flutter
  gsettings: ^0.1.1
  meta: ^1.3.0
  platform: ^3.0.0
  plugin_platform_interface: ^2.0.0
  xdg_directories: ^0.2.0
  xml: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.example.keyboard_info
        pluginClass: KeyboardInfoPlugin
      ios:
        pluginClass: KeyboardInfoPlugin
      macos:
        pluginClass: KeyboardInfoPlugin
      windows:
        pluginClass: KeyboardInfoPlugin
