name: keyboard_layout
description: Retrieves the system's active keyboard layout.
homepage: https://github.com/jpnurmi/keyboard_layout
repository: https://github.com/jpnurmi/keyboard_layout
issue_tracker: https://github.com/jpnurmi/keyboard_layout/issues
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.keyboard_layout
        pluginClass: KeyboardLayoutPlugin
      ios:
        pluginClass: KeyboardLayoutPlugin
      linux:
        pluginClass: KeyboardLayoutPlugin
      macos:
        pluginClass: KeyboardLayoutPlugin
      windows:
        pluginClass: KeyboardLayoutPlugin
