name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  desktop:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Install tools (Ubuntu)
      run: |
        sudo apt install -y cmake libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb
        echo "XKBLAYOUT=fi" > keyboard
        sudo mv keyboard /etc/default
      if: matrix.os == 'ubuntu-latest'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: beta
    - name: Configure Flutter
      run: flutter config --enable-linux-desktop --enable-macos-desktop --enable-windows-desktop --no-enable-web
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
    - name: Run integration tests (Ubuntu)
      run: xvfb-run -a flutter drive -v --driver=test_driver/integration_test.dart --target=integration_test/keyboard_layout_integration_test.dart
      working-directory: example
      if: matrix.os == 'ubuntu-latest'
    - name: Run integration tests (macOS & Windows)
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/keyboard_layout_integration_test.dart
      working-directory: example
      if: matrix.os != 'ubuntu-latest'

  android:
    runs-on: macos-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
    - name: Run integration tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd example && flutter drive -v --driver=test_driver/integration_test.dart --target=integration_test/keyboard_layout_integration_test.dart
