name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Install tools (Ubuntu)
      run: sudo apt install -y cmake libgtk-3-dev liblzma-dev ninja-build pkg-config
      if: matrix.os == 'ubuntu-latest'
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
    - name: Configure Flutter
      run: flutter config --enable-linux-desktop --enable-macos-desktop --enable-windows-desktop --no-enable-web
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
    - name: Run integration tests
      run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/keyboard_layout_integration_test.dart --no-sound-null-safety
      working-directory: example
